apiVersion: apps/v1

kind: Deployment

metadata:
  name: student-performance-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: student-performance-app

  template:

    metadata:
      labels:
        app: student-performance-app

    spec:

      containers:

      - name: student-performance-container

        image: l00196904/student-performance-app:08827595b17c4d6020115543f0fb04966e2d3356

        imagePullPolicy: Always

        ports:
        - containerPort: 5000
