apiVersion: v1

kind: Service

metadata:
  name: student-performance-service

spec:

  type: NodePort

  selector:
    app: student-performance-app

  ports:

    - protocol: TCP

      port: 80

      targetPort: 5000

      nodePort: 30007
