name: Upload Prediction Logs

on:

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:

  upload-logs:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Install Dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Create Service Account File

        run: |

          echo '${{ secrets.GCP_SERVICE_ACCOUNT }}' > service-account.json

      - name: Set Credentials

        run: |

          echo "GOOGLE_APPLICATION_CREDENTIALS=service-account.json" >> $GITHUB_ENV

      - name: Upload Prediction Logs

        run: |

          python -m src.upload_prediction_logs